### ISSUE TITLE
[BUG] Protocol error (Runtime.callFunctionOn): Promise was collected

### ISSUE THREAD

**Issue by narra-dev** [pguardiario/captchas#5]
**Describe the bug**
Always getting this error when running your script

**To Reproduce**
```
const puppeteer = require('puppeteer')
 
openURL()

function openURL(){

  (async () => {
    const browser = await puppeteer.launch({ headless: false })
    const page = await browser.newPage()
    await page.goto('https://backpack.tf/')
    await page.addScriptTag({url: "https://cdn.jsdelivr.net/gh/pguardiario/captchas/captchas.js"})
    let status = await page.evaluate(async () => {
      return new Promise((resolve, reject) => {
        solve(['06***********************6d', {}, resolve])
      })
    })

    switch(status){
      case 'NO_CAPTCHAS':
        console.log('no captcha found')
      case 'OK':
        console.log('captcha found!')
        break
      case 'ERROR_ZERO_BALANCE':
        console.log('no captcha balance')
      case 'ERROR_CAPTCHA_UNSOLVABLE':
        console.log('retrying')
        // try again ?
      default:
        debugger
    }

    await page.waitFor(10000)
  })()

}
```

**ERROR LOG:**
```
(node:35008) UnhandledPromiseRejectionWarning: Error: Protocol error (Runtime.callFunctionOn): Promise was collected
    at Promise (/Users/apple/Desktop/kwork/baza5000/telegram/node_modules/puppeteer/lib/Connection.js:183:56)
    at new Promise (<anonymous>)
    at CDPSession.send (/Users/apple/Desktop/kwork/baza5000/telegram/node_modules/puppeteer/lib/Connection.js:182:12)
    at ExecutionContext._evaluateInternal (/Users/apple/Desktop/kwork/baza5000/telegram/node_modules/puppeteer/lib/ExecutionContext.js:107:44)
    at ExecutionContext.evaluate (/Users/apple/Desktop/kwork/baza5000/telegram/node_modules/puppeteer/lib/ExecutionContext.js:48:23)
    at ExecutionContext.<anonymous> (/Users/apple/Desktop/kwork/baza5000/telegram/node_modules/puppeteer/lib/helper.js:112:23)
    at DOMWorld.evaluate (/Users/apple/Desktop/kwork/baza5000/telegram/node_modules/puppeteer/lib/DOMWorld.js:112:20)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  -- ASYNC --
    at Frame.<anonymous> (/Users/apple/Desktop/kwork/baza5000/telegram/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.evaluate (/Users/apple/Desktop/kwork/baza5000/telegram/node_modules/puppeteer/lib/Page.js:860:43)
    at Page.<anonymous> (/Users/apple/Desktop/kwork/baza5000/telegram/node_modules/puppeteer/lib/helper.js:112:23)
    at /Users/apple/Desktop/kwork/baza5000/telegram/2021BOT/automatic.js:24:29
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:35008) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:35008) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Any thoughts could be very helpful, thanks in advance.

**Comment by pguardiario** [comment]
Try it like this:
save the latest captchas.js locally (I don't trust the CDN cache)
add this after the goto:
`await page.waitForSelector('iframe')`
and change the addSciptTag line to:
`await page.addScriptTag({path: "captchas.js"})`
I just tested it and it worked.

**Comment by narra-dev** [comment]
Same error.
  
Code now looks like this right?
```
    await page.goto('https://backpack.tf/')
    await page.waitForSelector('iframe')
    await page.addScriptTag({path: "captchas.js"})
```

ERROR LOG
```
(node:42714) UnhandledPromiseRejectionWarning: Error: Protocol error (Runtime.callFunctionOn): Promise was collected
    at Promise (/Users/apple/Desktop/kwork/baza5000/telegram/node_modules/puppeteer/lib/Connection.js:183:56)
    at new Promise (<anonymous>)
    at CDPSession.send (/Users/apple/Desktop/kwork/baza5000/telegram/node_modules/puppeteer/lib/Connection.js:182:12)
    at ExecutionContext._evaluateInternal (/Users/apple/Desktop/kwork/baza5000/telegram/node_modules/puppeteer/lib/ExecutionContext.js:107:44)
    at ExecutionContext.evaluate (/Users/apple/Desktop/kwork/baza5000/telegram/node_modules/puppeteer/lib/ExecutionContext.js:48:23)
    at ExecutionContext.<anonymous> (/Users/apple/Desktop/kwork/baza5000/telegram/node_modules/puppeteer/lib/helper.js:112:23)
    at DOMWorld.evaluate (/Users/apple/Desktop/kwork/baza5000/telegram/node_modules/puppeteer/lib/DOMWorld.js:112:20)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  -- ASYNC --
    at Frame.<anonymous> (/Users/apple/Desktop/kwork/baza5000/telegram/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.evaluate (/Users/apple/Desktop/kwork/baza5000/telegram/node_modules/puppeteer/lib/Page.js:860:43)
    at Page.<anonymous> (/Users/apple/Desktop/kwork/baza5000/telegram/node_modules/puppeteer/lib/helper.js:112:23)
    at /Users/apple/Desktop/kwork/baza5000/telegram/2021BOT/automatic.js:26:29
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:42714) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:42714) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by pguardiario** [comment]
I'm not sure what's causing it but I can't reproduce it.
The script worked when I tried it.
